target-version = "py39" # python3.9
line-length = 120

[lint]
extend-select = [
  "C4",   # comprehensions
  "B",    # find bug-prone patterns
  "ARG",  # unused arguments
  "PL",   # Pylint codes
  "I",    # sort imports
  "PERF", # performance checks
  "D",    # docstring formatting
]
ignore = [
  "PLR",  # design-related Pylint codes
  "D100", # missing docstrings in module
  "D203", # blank line before class docstring
  "D213", # multi-line docstring on second line
]

[lint.pydocstyle]
convention = "numpy"
