target-version = "py39" # python3.9
line-length = 120

[lint]
extend-select = [
  "C4",   # comprehensions
  "B",    # find bug-prone patterns
  "ARG",  # unused arguments
  "PL",   # Pylint codes
  "I",    # Sort imports
]
ignore = [
  "PLR",      # design-related Pylint codes
]
